server/apps/PlacesRemember/urls.py
from apps.PlacesRemember.views import IndexView
from django.urls import path

urlpatterns = [
    path('', IndexView.as_view()),

]

server/apps/place/urls.py
from apps.place.views import PlaceView, GetAllPlacesView, AddPlaceFormVIew, DeleteAndGenerateTestPlaces
from django.urls import path

urlpatterns = [
    path('', PlaceView.as_view()),
    path('get_all_places/', GetAllPlacesView.as_view()),
    path('add_place/', AddPlaceFormVIew.as_view()),
    path('delete_and_generate_test_places/', DeleteAndGenerateTestPlaces.as_view()),

]

server/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path('', include('apps.PlacesRemember.urls')),
    path('place/', include('apps.place.urls')),
    path('admin/', admin.site.urls),
    path('', include('social_django.urls')),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

server/apps/PlacesRemember/models.py
from django.contrib.auth.models import User
from django.db import models


class UserAvatarModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_avatar')
    avatar = models.ImageField(upload_to='avatars')
    update_date = models.DateField(auto_now=True)

    class Meta:
        verbose_name = 'User avatar'
        verbose_name_plural = 'User avatars'

server/apps/place/models.py
from django.contrib.auth.models import User
from django.db import models


class PlaceModel(models.Model):
    title = models.CharField('Title', max_length=255)
    comment = models.TextField('Comment', max_length=1024)
    lat = models.DecimalField('Latitude', max_length=255, max_digits=9, decimal_places=6)
    lng = models.DecimalField('Longitude', max_length=255, max_digits=9, decimal_places=6)
    author = models.ForeignKey(User, verbose_name='Author', related_name='places', on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Place'
        verbose_name_plural = 'Places'
        ordering = ['-pub_date']

    def __str__(self):
        return self.title

server/apps/place/forms.py
from apps.place.models import PlaceModel
from django.forms import ModelForm


class PlaceForm(ModelForm):
    class Meta:
        model = PlaceModel
        fields = ['title', 'comment', 'lat', 'lng']

    def __init__(self, user, *args, **kwargs):
        self.author_id = user.id
        super(PlaceForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        place = super(PlaceForm, self).save(commit=False)
        place.author_id = self.author_id
        if commit:
            place.save()
        return place

server/apps/PlacesRemember/views.py
from django.shortcuts import render
from django.views import View


class IndexView(View):
    def get(self, request):
        return render(request, 'index.html')

server/apps/place/views.py
import random

from apps.place.forms import PlaceForm
from apps.place.models import PlaceModel
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views import View


@method_decorator(login_required, name='dispatch')
class PlaceView(View):
    def get(self, request):
        user = request.user
        content = get_user_places(request, user)
        return render(request, 'place/place.html', content)


def get_user_places(request, user):
    places = user.places.all()
    paginator = Paginator(places, 15)
    page_number = request.GET.get('page', 1)
    page_object = paginator.get_page(page_number)
    return {'page_obj': page_object}


@method_decorator(login_required, name='dispatch')
class GetAllPlacesView(View):
    def get(self, request):
        user = request.user
        features = []
        for place in user.places.all():
            features.append({
                'type': 'Feature',
                'properties': {
                    'balloonContent': f'{place.title}<br>{place.comment}',
                },
                'geometry': {
                    'type': 'Point',
                    'coordinates': [place.lat, place.lng],
                }
            })
        response_dict = {
            'type': 'FeatureCollection',
            'features': features,
        }
        return JsonResponse(response_dict)


class AddPlaceFormVIew(View):
    def get(self, request):
        form = PlaceForm(request.user)
        return render(request, 'place/add_place.html', {
            'form': form,
        })

    def post(self, request):
        form = PlaceForm(request.user, request.POST)
        user = request.user
        if form.is_valid():
            form.cleaned_data.update({
                'author_id': user.id,
            })
            form.save()
            return HttpResponseRedirect('/place')
        else:
            return render(request, 'place/add_place.html', {
                'form': form,
            })


class DeleteAndGenerateTestPlaces(View):
    def get(self, request):
        request.user.places.all().delete()
        for i in range(50):
            tmp_object = PlaceModel()
            tmp_object.title = f"Test title {i}"
            tmp_object.comment = f"Test comment {i}"
            tmp_object.lat = random.uniform(55.997097, 56.019986)
            tmp_object.lng = random.uniform(92.771205, 92.965182)
            tmp_object.author_id = request.user.id
            tmp_object.save()
        return HttpResponseRedirect('/place')

server/templates/base.html
<!doctype html>
{% load static %}
{% load tags %}
{% load trans from i18n %}
{% block head %}
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta charset="utf-8">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static "css/materialize.min.css" %}">
        <script src="{% static "js/materialize.min.js" %}"></script>

        <style>
            .header, .main {
                padding-left: 300px;
            }

            @media only screen and (max-width: 992px) {
                .header, .main {
                    padding-left: 0;
                }
            }
        </style>

        {% block css %}
        {% endblock %}

        {% block js %}
        {% endblock %}


    </head>

{% endblock %}

<body>

<!-- Nav bar -->
<nav class="blue header" style="z-index: 3; margin-bottom: 3px">
    <div class="nav-wrapper container">
        <a href="/" class="brand-logo center white-text">PlacesRemember</a>
        <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
</nav>

<!-- Side nav -->
<ul class="sidenav sidenav-fixed container" id="nav-mobile">
    {% if not user.is_authenticated %}
        <li><a class="black-text" href="/login/vk-oauth2">Login via VK</a></li>
        <li><a class="black-text" href="/login/facebook">Login via Facebook</a></li>
    {% else %}
        <li>
            <div class="user-view">
                <div class="background" style="background-color: #1e88e5;">
                </div>
                <img class="circle" src="{{ user.user_avatar.avatar.url }}">
                <span class="white-text name">{{ user.first_name }} {{ user.last_name }}</span>
                <span class="white-text email">{{ user.email }}</span>
            </div>
        </li>
        <li id="my_places_btn"><a class="black-text" href="/place">My Places</a></li>
        <li><a class="black-text" href="/logout">Logout</a></li>
    {% endif %}
</ul>


<!-- Content -->
<div class="container main" style="margin-top: 20px;">
    {% block content %}
    {% endblock %}
</div>


<!-- Activate Side nav -->
<script>

    document.addEventListener('DOMContentLoaded', function () {
        let elems = document.querySelectorAll('.sidenav');
        let instances = M.Sidenav.init(elems, {
            draggable: true,
            dragTargetWidth: '100%',
        });
    });

</script>

{% block end_js %}
{% endblock %}
</body>

server/templates/index.html
{% extends "base.html" %}
{% block title %}PlacesRemember{% endblock %}

{% block content %}

<div class="section no-pad-bot" id="index-banner">
      <br><br>
      <div class="row center">
        <h5 class="col s12 light">Here you can store your impressions of the places visited </h5>
      </div>
  </div>

{% endblock %}

server/templates/place/add_place.html
{% extends "base.html" %}
{% load tags %}
{% block title %}Add new Place{% endblock %}

{% block content %}

    <div id="map" style="height: 400px;"></div><br>
    <sup>Select a place on the map</sup>

    <div>
        <form action="/place/add_place/" method="post">
            {% csrf_token %}
            <div class="input-field">
                <label for="id_title">Title</label>
                <input type="text" name="title" maxlength="255" required="" id="id_title">
            </div>
            <div class="input-field">
                <label for="id_comment">Comment</label>
                <textarea name="comment" cols="40" rows="10"
                          maxlength="1024"
                          required="" id="id_comment" class="materialize-textarea"></textarea>
            </div>
            <p style="display: none;"><label for="id_lat">Latitude:</label> <input type="number" name="lat"
                                                                                   step="0.000001" required=""
                                                                                   id="id_lat">
            </p>
            <p style="display: none"><label for="id_lng">Longitude:</label> <input type="number" name="lng"
                                                                                   step="0.000001" required=""
                                                                                   id="id_lng">
            </p>
            <button class="btn waves-effect waves-light blue" type="submit" name="action">Submit
                <i class="material-icons right">send</i>
            </button>
        </form>
    </div>


{% endblock %}

{% block end_js %}
    <script src="https://api-maps.yandex.ru/2.1/?lang=en_US&amp;apikey={% get_yandex_api_key %}"
            type="text/javascript"></script>
    <script>

        ymaps.ready(init);

        function init() {
            let map = new ymaps.Map("map", {
                center: [56.007870, 92.853259],
                zoom: 15
            });

            map.events.add('click', function (e) {
                let lat_field = document.getElementsByName('lat')[0],
                    lng_field = document.getElementsByName('lng')[0];
                if (!map.balloon.isOpen()) {
                    var coords = e.get('coords');
                    map.balloon.open(coords, {
                        contentHeader: 'New places is here',
                    });
                    lat_field.value = coords[0].toPrecision(8);
                    lng_field.value = coords[1].toPrecision(8);
                    console.log(coords[0].toPrecision(8), coords[1].toPrecision(8))
                } else {
                    map.balloon.close();
                    lat_field.value = '';
                    lng_field.value = '';
                }
            });

        }
    </script>
{% endblock %}

server/templates/place/place.html
{% extends "base.html" %}
{% load tags %}
{% block title %}My Places{% endblock %}


{% block content %}
    <div class="center" id="no_place_text" style="display: none">
        <br><br>
        <h5 class="light">You don't have a single place memory</h5>
    </div>

    <!-- Places list -->
    <div class="row">
        {% for place in page_obj %}

            <div class="col s12 m6 l4">
                <a class="modal-trigger" href="#modal{{ place.id }}">
                    <div class="card-panel light-blue lighten-5 z-depth-1">
                        <h6><span class="black-text" style="word-break: break-all;">{{ place.title | truncatechars:35 }}
                        </span></h6>
                    </div>
                </a></div>

            <!-- Modal -->

            <div id="modal{{ place.id }}" class="modal">
                <div class="modal-content" style="word-break: break-all;">
                    <h5>{{ place.title }}</h5>
                    <p>{{ place.comment }}</p>
                    <div class="hiddendiv lat" id="lat{{ place.id }}">{{ place.lat }}</div>
                    <div class="hiddendiv lng" id="lng{{ place.id }}">{{ place.lng }}</div>
                </div>
                <br>
                <div id="map{{ place.id }}" class="map" style="height: 400px; margin: 20px;"></div>
            </div>

        {% endfor %}
    </div>


    <!-- Map button -->
    <a id="map_btn" class="waves-effect waves-light btn modal-trigger btn-floating blue btn-large"
       href="#map_modal" style="position: fixed; bottom: 45px; right: 95px;">
        <i class="material-icons">map</i>
    </a>

    <div id="map_modal" class="modal">
        <div class="modal-content">
            <h5>All places</h5>
        </div>
        <br>

        <div class="progress blue lighten-4">
            <div class="indeterminate blue"></div>
        </div>
        <div id="all_places_map" class="map" style="height: 400px; margin: 20px;"></div>
    </div>


    <!-- Add button -->
    <a id="add_btn" class="waves-effect waves-light btn btn-floating blue btn-large"
       href="add_place/" style="position: fixed; bottom: 45px; right: 25px;">
        <i class="material-icons">add</i>
    </a>

    <!-- Magic button aura -->
    <div class="tap-target light-blue lighten-3" data-target="add_btn">
        <div class="tap-target-content">
            <h5>Add new place</h5>
        </div>
    </div>

    <!-- Pagination -->
    {% if page_obj.paginator.num_pages > 1 %}
        <ul class="pagination center-align">
            {% if page_obj.has_previous %}
                <li class="waves-effect"><a href="?page={{ page_obj.previous_page_number }}">
                    <i class="material-icons">chevron_left</i></a></li>
            {% else %}
                <li class="disabled"><a href="#!">
                    <i class="material-icons">chevron_left</i></a></li>
            {% endif %}

            {% for num_page in page_obj.paginator.page_range %}
                {% if num_page == page_obj.number %}
                    <li class="active blue"><a href="?page={{ num_page }}">{{ num_page }}</a></li>
                {% else %}
                    <li class="waves-effect"><a href="?page={{ num_page }}">{{ num_page }}</a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="waves-effect"><a href="?page={{ page_obj.next_page_number }}">
                    <i class="material-icons">chevron_right</i></a></li>
            {% else %}
                <li class="disabled"><a href="#!">
                    <i class="material-icons">chevron_right</i></a></li>
            {% endif %}
        </ul>
    {% endif %}


{% endblock %}

<!-- Hidden my places button -->
{% block css %}
    <style>
        #my_places_btn {
            display: none;
        }
    </style>
{% endblock %}

<!-- Init yandex map api -->
{% block js %}

    <script src="https://api-maps.yandex.ru/2.1/?lang=en_US&amp;apikey={% get_yandex_api_key %}"
            type="text/javascript"></script>

{% endblock %}

{% block end_js %}

    {% if page_obj.paginator.count == 0 %}
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                let elems = document.querySelectorAll('.tap-target');
                let instances = M.TapTarget.init(elems[0]);
                instances.open();
                let hidden_text = document.getElementById('no_place_text');
                hidden_text.style.display = 'block';
            });
        </script>
    {% endif %}
    {% if page_obj.paginator.count <= 1 %}
        <script>
            document.addEventListener('DOMContentLoaded', function () {
                let map_button = document.getElementById('map_btn');
                map_button.style.display = 'none';
            });
        </script>
    {% endif %}
    <script>

        function open_map(modal_id) {
            map_element = modal_id.getElementsByClassName('map')[0].id;
            if (map_element === "all_places_map") {
                view_all_places(map_element);
                return;
            }
            let lat = parseFloat(modal_id.getElementsByClassName('lat')[0].textContent);
            let lng = parseFloat(modal_id.getElementsByClassName('lng')[0].textContent);
            let map = new ymaps.Map(map_element, {
                center: [lat, lng],
                zoom: 15,
            });
            let point = new ymaps.GeoObject({
                geometry: {
                    type: "Point",
                    coordinates: [lat, lng]
                }
            });
            map.geoObjects.add(point);
        }

        function close_map(modal_id) {
            //TODO: remove map after closing this modal
        }

        function view_all_places(map_element) {
            fetch("/place/get_all_places")
                .then(response => response.json())
                .then((data) => {
                    let preloader = document.getElementsByClassName('progress')[0];
                    preloader.remove();
                    let points = ymaps.geoQuery(data)
                    let map = new ymaps.Map(map_element, {
                        center: [55.76, 37.64],
                        zoom: 10,
                    });
                    map.geoObjects.add(points.clusterize());
                    map.setBounds(points.getBounds(), {zoomMargin: [30, 30, 30, 30]});
                    map.setZoom(map.getZoom());

                });
        }

        document.addEventListener('DOMContentLoaded', function () {
            let all_modals = document.querySelectorAll('.modal');
            let instances = M.Modal.init(all_modals, {
                onOpenEnd: open_map,
                onCloseEnd: close_map,
            });
        });

    </script>
{% endblock %}